eUseControl.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eUseControl.Web.Extension;
using eUseControl.Models;

namespace eUseControl.Web.Controllers
{
    public class ContactController : BaseController
    {
        // GET: Contact
        public ActionResult Index()
        {
            SessionStatus();
            if ((string)System.Web.HttpContext.Current.Session["LoginStatus"] != "login")
            {
                return RedirectToAction("Index", "Login");
            }
            var user = System.Web.HttpContext.Current.GetMySessionObject();
            UserData u = new UserData
            {
                Username = user.Username,
                Level = user.Level,
                Id = user.Id,
                Email = user.Email
            };
            return View(u);
        }
    }
}

eUseControl.Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eUseControl.BusinessLogic;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.User;
using eUseControl.Web.Models;
using eUseControl.Helpers;

namespace eUseControl.Web.Controllers
{
    public class RegisterController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        private readonly ISession _session;
        public RegisterController()
        {
            var bl = new BussinesLogic();
            _session = bl.GetSessionBL();
        }

        [HttpPost]
        public ActionResult Index(UserRegister data)
        {
            if (ModelState.IsValid)
            {
                URegisterData login = new URegisterData
                {
                    Email = data.Email,
                    Username = data.Username,
                    Password = LoginHelper.HashGen(data.Password),
                    RegisterDateTime = DateTime.Now,
                };

                var userRegistration = _session.UserRegister(login);
                if (userRegistration.Status)
                {
                    ViewBag.Name = "Successsful registration";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", userRegistration.StatusMsg);
                    return View();
                }
            }
            return View();
        }
    }
}

eUseControl.Web/Views/Shared/_Footer.cshtml
@{
    ViewBag.Title = "_Footer";
}

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6">
                    <div class="footer-info">
                        <h3>Restaurantly</h3>
                        <p>
                            A108 Adam Street <br>
                            NY 535022, USA<br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>

                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Restaurantly</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/restaurantly-restaurant-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

eUseControl.Web/Views/Shared/_Header.cshtml
@using System.Linq
@using eUseControl.Domain.Enums
@using eUseControl.Web.Extension
@using eUseControl.Helpers;
@using WebMatrix.Data;
@using eUseControl.BuisnessLogic.DBModel
@using eUseControl.Web.Controllers;

<header id="header" class="fixed-top d-flex align-items-cente">



    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

        <h1 class="logo me-auto me-lg-0"><a href="@Url.Action("Index","Home")">Restaurantly</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
                <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
                <li><a class="nav-link scrollto" href="#about">About</a></li>
                <li><a class="nav-link scrollto" href="#menu">Menu</a></li>
                <li><a class="nav-link scrollto" href="#specials">Specials</a></li>
                <li><a class="nav-link scrollto" href="#events">Events</a></li>
                <li><a class="nav-link scrollto" href="#chefs">Chefs</a></li>
                <li><a class="nav-link scrollto" href="#gallery">Gallery</a></li>
                <li><a class="nav-link scrollto" href="@Url.Action("Index", "Contact")">Contact</a></li>
                <li class="dropdown">
                    <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                    <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown">
                            <a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                            <ul>
                                <li><a href="#">Deep Drop Down 1</a></li>
                                <li><a href="#">Deep Drop Down 2</a></li>
                                <li><a href="#">Deep Drop Down 3</a></li>
                                <li><a href="#">Deep Drop Down 4</a></li>
                                <li><a href="#">Deep Drop Down 5</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                    </ul>
                </li>

            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->
        @if (Session["Username"] != null)
        {
            <a href="#" class="book-a-table-btn scrollto d-none d-lg-flex">@Session["Username"]</a>
            <a href="@Url.Action("Logout","Login")">Logout</a>
            var user1 = System.Web.HttpContext.Current.GetMySessionObject();

            if (user1.Level == URole.Admin)
            {
                <a class="book-a-table-btn scrollto d-none d-lg-flex" href="@Url.Action("Index","Admin")">AdminPanel</a>
            }
        }
        else
        {
            <a href="@Url.Action("Index", "Login")" class="book-a-table-btn scrollto d-none d-lg-flex">Log In</a>
            <a href="@Url.Action("Index", "Register")" class="book-a-table-btn scrollto d-none d-lg-flex">Sign In</a>
        }

    </div>

</header>

eUseControl.Web/Views/Shared/_Layout _Blank.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eUse System | @ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/animate.min/css")

    @Styles.Render("~/bundles/aos/css")

    @Styles.Render("~/bundles/bootstrap.min/css")

    @Styles.Render("~/bundles/bootstrap-icons/css")
    @Styles.Render("~/bundles/glightbox.min/css")
    @Styles.Render("~/bundles/swiper-bundle.min/css")

    @Styles.Render("~/bundles/style/css")






    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>

<body>





    @RenderBody()

 



    @Scripts.Render("~/bundles/aos/js")
   
    @Scripts.Render("~/bundles/glightbox.min/js")
    @Scripts.Render("~/bundles/isotope.pkgd.min/js")
    @Scripts.Render("~/bundles/validate/js")
    @Scripts.Render("~/bundles/swiper-bundle.min/js")
   
    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)
    
</body>
</html>

eUseControl.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eUse System | @ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/animate.min/css")

    @Styles.Render("~/bundles/aos/css")

    @Styles.Render("~/bundles/bootstrap.min/css")

    @Styles.Render("~/bundles/bootstrap-icons/css")
    @Styles.Render("~/bundles/glightbox.min/css")
    @Styles.Render("~/bundles/swiper-bundle.min/css")

    @Styles.Render("~/bundles/style/css")






    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>

<body>



    @Html.Partial("_TopBar")

    @Html.Partial("_Header")

    @Html.Partial("_Navigation")


    @RenderBody()

    @Html.Partial("_Footer")



    @Scripts.Render("~/bundles/aos/js")
   
    @Scripts.Render("~/bundles/glightbox.min/js")
    @Scripts.Render("~/bundles/isotope.pkgd.min/js")
    @Scripts.Render("~/bundles/validate/js")
    @Scripts.Render("~/bundles/swiper-bundle.min/js")
   
    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)
    
</body>
</html>

eUseControl.Web/Views/Shared/_LayoutContact.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eUse System | @ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/animate.min/css")

    @Styles.Render("~/bundles/aos/css")

    @Styles.Render("~/bundles/bootstrap.min/css")

    @Styles.Render("~/bundles/bootstrap-icons/css")
    @Styles.Render("~/bundles/glightbox.min/css")
    @Styles.Render("~/bundles/swiper-bundle.min/css")

    @Styles.Render("~/bundles/style/css")






    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>

<body>



    @Html.Partial("_TopBar")

    @Html.Partial("_Header")

    


    @RenderBody()

    @Html.Partial("_Footer")



    @Scripts.Render("~/bundles/aos/js")

    @Scripts.Render("~/bundles/glightbox.min/js")
    @Scripts.Render("~/bundles/isotope.pkgd.min/js")
    @Scripts.Render("~/bundles/validate/js")
    @Scripts.Render("~/bundles/swiper-bundle.min/js")

    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)

</body>
</html>

eUseControl.Web/Views/Shared/_LayoutLogin.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eUse System | @ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/animate.min/css")

    @Styles.Render("~/bundles/aos/css")

    @Styles.Render("~/bundles/bootstrap.min/css")

    @Styles.Render("~/bundles/bootstrap-icons/css")
    @Styles.Render("~/bundles/glightbox.min/css")
    @Styles.Render("~/bundles/swiper-bundle.min/css")

    @Styles.Render("~/bundles/style/css")






    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>

<body>



    @Html.Partial("_TopBar")

    @Html.Partial("_Header")




    @RenderBody()

    @Html.Partial("_Footer")



    @Scripts.Render("~/bundles/aos/js")

    @Scripts.Render("~/bundles/glightbox.min/js")
    @Scripts.Render("~/bundles/isotope.pkgd.min/js")
    @Scripts.Render("~/bundles/validate/js")
    @Scripts.Render("~/bundles/swiper-bundle.min/js")

    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)

</body>
</html>

eUseControl.Web/Views/Shared/_LayoutSingin.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>eUse System | @ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/animate.min/css")

    @Styles.Render("~/bundles/aos/css")

    @Styles.Render("~/bundles/bootstrap.min/css")

    @Styles.Render("~/bundles/bootstrap-icons/css")
    @Styles.Render("~/bundles/glightbox.min/css")
    @Styles.Render("~/bundles/swiper-bundle.min/css")

    @Styles.Render("~/bundles/style/css")






    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>

<body>



    @Html.Partial("_TopBar")

    @Html.Partial("_Header")




    @RenderBody()

    @Html.Partial("_Footer")



    @Scripts.Render("~/bundles/aos/js")

    @Scripts.Render("~/bundles/glightbox.min/js")
    @Scripts.Render("~/bundles/isotope.pkgd.min/js")
    @Scripts.Render("~/bundles/validate/js")
    @Scripts.Render("~/bundles/swiper-bundle.min/js")

    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)

</body>
</html>

eUseControl.Web/Views/Shared/_TopBar.cshtml
@{
    ViewBag.Title = "_TopBar";
}



<!-- ======= Top Bar ======= -->
<div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-center justify-content-md-between">

        <div class="contact-info d-flex align-items-center">
            <i class="bi bi-phone d-flex align-items-center"><span>+37378127555</span></i>
            <i class="bi bi-clock d-flex align-items-center ms-4"><span> Mon-Sat: 11AM - 23PM</span></i>
        </div>

        <div class="languages d-none d-md-flex align-items-center">
            <ul>
                <li>En</li>
                <li><a href="#">De</a></li>
            </ul>
        </div>
    </div>
</div>